name: togglemaster

networks:
  infra-net:
  service-backbone:

services:

  evaluation-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    networks:
      - infra-net
      - service-backbone

    depends_on:
      shared-redis:
        condition: service_healthy
      localstack:
        condition: service_healthy
      auth-app:
        condition: service_healthy
      flag-app:
        condition: service_healthy
      targeting-app:
        condition: service_healthy

    env_file:
      - .env

    ports:
      - "8004:8004"

    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8004/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
