name: togglemaster

# Centralized Infrastructure and Shared Resources

networks:
  infra-net:
    driver: bridge
  service-backbone:
    driver: bridge

services:

  shared-redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - infra-net
      - service-backbone
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:latest
    restart: unless-stopped
    networks:
      - infra-net
      - service-backbone
    ports:
      - "4566:4566"
    environment:
      SERVICES: sqs
      DEFAULT_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
    volumes:
      - ./infra/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4566/_localstack/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10

  shared-dynamodb:
    image: amazon/dynamodb-local:latest
    restart: unless-stopped
    networks:
      - infra-net
      - service-backbone
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - ./infra/dynamodb:/home/dynamodblocal/data
