apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: togglemaster
data:
  # Database hosts (RDS)
  AUTH_DB_HOST: "togglemaster-auth.c36kciuseu7k.us-east-1.rds.amazonaws.com"
  FLAG_DB_HOST: "togglemaster-flags.c36kciuseu7k.us-east-1.rds.amazonaws.com"
  TARGETING_DB_HOST: "togglemaster-targeting.c36kciuseu7k.us-east-1.rds.amazonaws.com"
  REDIS_HOST: "togglemaster-cache-6cviqx.serverless.use1.cache.amazonaws.com:6379"
  REDIS_TLS: "true"
  # URLs de servicos internos (comunicacao entre microservicos)
  AUTH_SERVICE_URL: "http://auth-service:8001"
  FLAG_SERVICE_URL: "http://flag-service:8002"
  TARGETING_SERVICE_URL: "http://targeting-service:8003"
  EVALUATION_SERVICE_URL: "http://evaluation-service:8004"
  ANALYTICS_SERVICE_URL: "http://analytics-service:8005"
  # Configuracoes AWS
  AWS_REGION: "us-east-1"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/154367514500/togglemaster-analytics-queue"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
