# ==========================================
# SECRETS DA APLICACAO
# ==========================================
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: togglemaster
type: Opaque
data:
  # Valores codificados em base64 (Senha: Tech654987)
  POSTGRES_USER: "cG9zdGdyZXM=" # "postgres"
  POSTGRES_PASSWORD: "VGVjaDY1NDk4Nw==" # "Tech654987"
  MASTER_KEY: "VGVjaDY1NDk4Nw==" # "Tech654987"

---
# ==========================================
# CREDENCIAIS AWS
# ==========================================
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: togglemaster
type: Opaque
data:
  # Estas chaves devem ser atualizadas sempre que o lab AWS expirar
  AWS_ACCESS_KEY_ID: "QVNJQTQ3Q1JYQ1I2VkVHNVU1VTM="
  AWS_SECRET_ACCESS_KEY: "bitN3XUzKzl0bmlxQlZzS3A0bGs0THE3YlJUTHFpMmpoNUkyR2tjYjU="
  AWS_SESSION_TOKEN: "SVFvSmIzSnpiM2x6Ym1ScGJuWnZjRVB2Ly8vLy8vLy8vL3dFYUNYWmx6d2VjLXF1ZXRNRElKTUVZQ0lRQ1dKYkNoZnZmWHlSOHpzdmc1alBBaUtTZEJ1YWhsNzFBTXdrbmRjNmRxbFFJaEEwNTloaXkwY1N3TWx0MDA0TGpwZkZzNmlUSVB4YWE4Z3BHc2QrSzV0NU8rS3E4Q0NNVC8vLy8vLy8vLy93RVFBQm9NT2RreE03QzBNMUlnK25ndDZIRTA2bUo0ZHI4UXFnd0lhNjNObTdaMm9NNmlGNktjUXZDekp1M0IwZCtLbkdNZWlDdTVweTZHZFFCRlFya25EMVQ3Y0EwOHZFWUlUUQlCbGNDdytPbXlpYjRwUkRxWW1IcjNBVlZLK0pQL3EwYUNxaG94RDdraVQ0M3NPTHZ1NFgvRjlUZDNDTGNSdWFPanFYV0FIT3JWWWFUV1pmbG5hV0krdnU2MGg0N0Z0SGNqZGhmVTV6UUxRdytWK1l0Tm9IRUIyUit5WEhocDNJcEFTM0FqdGNQdUxtQ3RCMm8wbWl2SHc1enIwU1RpZ0NKYThVbFJsUGtpTmZwZlB4cmExUFRvcHBIM2hRN0dTUjR3OENJTHBvQ2pUMDhOZDg5YUhyZUJncHBHYWlDMkZxcDl3T2NtMmMzM2lxcHQ2bVV4cHVCTUzzTmdQOUJEbkNPRWdJQjV3WEUzNjNSR1RoZWZTRjByME1QbmoyODBHT3B3QlAyMFlvTVlHUmQxREtrc2w0SThpQkp2WkQvajFFZnRUZld4REpUallxTVI0L2ZDNnNUOERpRy9tSElPdCtnbjQwaFJOZTMxZWtTcHBkNjVSZ0s4ZzZ5UTR1N3Z2dkU2ZS9HT2t5K2h1VU9tNUxPRm9Mcmd1bEZBM3dkWGJFei9pZ0lRNlZqKzh2VFpSV3cvYlBmSGVDcGVMUC9lZklOaDRkcGhoQXFNSUZXakE4Q3J0OWhvb2NzVXI5SXJXT3R4L3B4dTJEaDh4TXVJbXVwcw=="
