apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: togglemaster
type: Opaque
data:
  # Valores em base64
  # Para gerar: echo -n "valor" | base64
  POSTGRES_USER: postgres           # "admin"
  POSTGRES_PASSWORD: dG9nZ2xlbWFzdGVyIzEyMzQ=  # "Password123" (substituir!)


