apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: togglemaster
data:
  AUTH_DB_HOST: "togglemaster-auth.c36kciuseu7k.us-east-1.rds.amazonaws.com"
  FLAG_DB_HOST: "togglemaster-flags.c36kciuseu7k.us-east-1.rds.amazonaws.com"
  TARGETING_DB_HOST: "togglemaster-targeting.c36kciuseu7k.us-east-1.rds.amazonaws.com"

  REDIS_HOST: "togglemaster-cache-6cviqx.serverless.use1.cache.amazonaws.com:6379"
  REDIS_TLS: "true"
  REDIS_URL: "redis://togglemaster-cache-6cviqx.serverless.use1.cache.amazonaws.com:6379"

  AUTH_SERVICE_URL: "http://auth-service:8001"
  FLAG_SERVICE_URL: "http://flag-service:8002"
  TARGETING_SERVICE_URL: "http://targeting-service:8003"
  EVALUATION_SERVICE_URL: "http://evaluation-service:8004"
  ANALYTICS_SERVICE_URL: "http://analytics-service:8005"

  AWS_REGION: "us-east-1"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/154367514500/togglemaster-analytics-queue"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"

  AWS_SQS_ENDPOINT_URL: ""
  AWS_DYNAMODB_ENDPOINT_URL: ""

  AUTH_DATABASE_URL: "postgres://postgres:Togglemaster123@togglemaster-auth.c36kciuseu7k.us-east-1.rds.amazonaws.com:5432/auth_db"
  FLAG_DATABASE_URL: "postgres://postgres:Togglemaster123@togglemaster-flags.c36kciuseu7k.us-east-1.rds.amazonaws.com:5432/flags_db"
  TARGETING_DATABASE_URL: "postgres://postgres:Togglemaster123@togglemaster-targeting.c36kciuseu7k.us-east-1.rds.amazonaws.com:5432/targeting_db"
